
[workspace]
members = [
    "boot",
    "kernel",
    "lib/*",
]
exclude = [
    "build",
]

[workspace.metadata.chos]
projects = [
    "boot",
    "kernel",
]
flags = [
    "-Zbuild-std=core,alloc",
    "-Zbuild-std-features=compiler-builtins-mem"
]
