#!/bin/bash

cwd=$(realpath $(dirname $0))

pushd $cwd &> /dev/null

cmd="cargo doc --workspace --document-private-items --no-deps -Zbuild-std=core,alloc --target arch/x86_64-chos.json"
echo $cmd
exec $cmd

e=$?

popd &> /dev/null
exit $e
