[package]
name = "chos-fs-initrd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chos = { path = "../../../kernel" }
chos-lib = { path = "../../../lib/chos-lib" }
