[package]
name = "chos-boot"
version = "0.1.0"
authors = ["chrou"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
chos-boot-defs = { path = "../lib/chos-boot-defs" }
chos-elf = { path = "../lib/chos-elf" }
chos-lib = { path = "../lib/chos-lib", default-features = false }
modular-bitfield = "0.11.2"
multiboot2 = "0.10.1"
rustc-demangle = "0.1.18"
spin = "0.7.1"
static_assertions = "1.1.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14.1"
chos-x64 = { path = "../lib/chos-x64" }
raw-cpuid = "9.0.0"