[package]
name = "chos"
version = "0.1.0"
authors = ["Christian Harper-Cyr <charpercyr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['dylib']

[dependencies]
paste = "1.0.4"
cfg-if = "1.0.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.13.2"
chos-x64 = { path = "../lib/chos-x64" }
