[package]
name = "chos"
version = "0.1.0"
authors = ["Christian Harper-Cyr <charpercyr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['dylib']

[dependencies]
bitflags = "1.2.1"
cfg-if = "1.0.0"
chos-config = { path = "../lib/chos-config" }
chos-lib = { path = "../lib/chos-lib", features = ["alloc"] }
chos-boot-defs = { path = "../lib/chos-boot-defs" }
modular-bitfield = "0.11.2"
multiboot2 = "0.10.1"
paste = "1.0.4"
spin = "0.7.1"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14.1"
chos-x64 = { path = "../lib/chos-x64" }
