
[meta]
include = [
    "arch/${ARCH}/project.toml"
]

[project]
deploy = "/chos/chos.elf"

[project.debug]
flags = ["--features=chos-lib/log-debug"]

[project.release]
flags = ["--features=chos-lib/log-info"]