#![no_std]
#![no_main]
#![allow(incomplete_features)]
#![feature(abi_x86_interrupt)]
#![feature(asm)]
#![feature(decl_macro)]
#![feature(destructuring_assignment)]
#![feature(fn_traits)]
#![feature(global_asm)]
#![feature(inline_const)]
#![feature(never_type)]
#![feature(once_cell)]
#![feature(unboxed_closures)]

mod arch;
